// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_management.proto

package org.example.proto;

public final class OrderManagementOuterClass {
  private OrderManagementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.proto.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>repeated string items = 2;</code>
     * @return A list containing the items.
     */
    java.util.List<java.lang.String>
        getItemsList();
    /**
     * <code>repeated string items = 2;</code>
     * @return The count of items.
     */
    int getItemsCount();
    /**
     * <code>repeated string items = 2;</code>
     * @param index The index of the element to return.
     * @return The items at the given index.
     */
    java.lang.String getItems(int index);
    /**
     * <code>repeated string items = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the items at the given index.
     */
    com.google.protobuf.ByteString
        getItemsBytes(int index);

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>float price = 4;</code>
     * @return The price.
     */
    float getPrice();

    /**
     * <code>string destination = 5;</code>
     * @return The destination.
     */
    java.lang.String getDestination();
    /**
     * <code>string destination = 5;</code>
     * @return The bytes for destination.
     */
    com.google.protobuf.ByteString
        getDestinationBytes();
  }
  /**
   * Protobuf type {@code org.example.proto.Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.proto.Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      id_ = "";
      items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      description_ = "";
      destination_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Order();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.OrderManagementOuterClass.Order.class, org.example.proto.OrderManagementOuterClass.Order.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList items_;
    /**
     * <code>repeated string items = 2;</code>
     * @return A list containing the items.
     */
    public com.google.protobuf.ProtocolStringList
        getItemsList() {
      return items_;
    }
    /**
     * <code>repeated string items = 2;</code>
     * @return The count of items.
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated string items = 2;</code>
     * @param index The index of the element to return.
     * @return The items at the given index.
     */
    public java.lang.String getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated string items = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the items at the given index.
     */
    public com.google.protobuf.ByteString
        getItemsBytes(int index) {
      return items_.getByteString(index);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_ = 0F;
    /**
     * <code>float price = 4;</code>
     * @return The price.
     */
    @java.lang.Override
    public float getPrice() {
      return price_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object destination_ = "";
    /**
     * <code>string destination = 5;</code>
     * @return The destination.
     */
    @java.lang.Override
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      }
    }
    /**
     * <code>string destination = 5;</code>
     * @return The bytes for destination.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      for (int i = 0; i < items_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, items_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (java.lang.Float.floatToRawIntBits(price_) != 0) {
        output.writeFloat(4, price_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destination_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destination_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < items_.size(); i++) {
          dataSize += computeStringSizeNoTag(items_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getItemsList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (java.lang.Float.floatToRawIntBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destination_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destination_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.OrderManagementOuterClass.Order)) {
        return super.equals(obj);
      }
      org.example.proto.OrderManagementOuterClass.Order other = (org.example.proto.OrderManagementOuterClass.Order) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (java.lang.Float.floatToIntBits(getPrice())
          != java.lang.Float.floatToIntBits(
              other.getPrice())) return false;
      if (!getDestination()
          .equals(other.getDestination())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.OrderManagementOuterClass.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.OrderManagementOuterClass.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.proto.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.proto.Order)
        org.example.proto.OrderManagementOuterClass.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.OrderManagementOuterClass.Order.class, org.example.proto.OrderManagementOuterClass.Order.Builder.class);
      }

      // Construct using org.example.proto.OrderManagementOuterClass.Order.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        price_ = 0F;
        destination_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_Order_descriptor;
      }

      @java.lang.Override
      public org.example.proto.OrderManagementOuterClass.Order getDefaultInstanceForType() {
        return org.example.proto.OrderManagementOuterClass.Order.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.OrderManagementOuterClass.Order build() {
        org.example.proto.OrderManagementOuterClass.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.OrderManagementOuterClass.Order buildPartial() {
        org.example.proto.OrderManagementOuterClass.Order result = new org.example.proto.OrderManagementOuterClass.Order(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.example.proto.OrderManagementOuterClass.Order result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          items_ = items_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.items_ = items_;
      }

      private void buildPartial0(org.example.proto.OrderManagementOuterClass.Order result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.destination_ = destination_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.OrderManagementOuterClass.Order) {
          return mergeFrom((org.example.proto.OrderManagementOuterClass.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.OrderManagementOuterClass.Order other) {
        if (other == org.example.proto.OrderManagementOuterClass.Order.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        if (!other.getDestination().isEmpty()) {
          destination_ = other.destination_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureItemsIsMutable();
                items_.add(s);
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 37: {
                price_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 42: {
                destination_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          items_ = new com.google.protobuf.LazyStringArrayList(items_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string items = 2;</code>
       * @return A list containing the items.
       */
      public com.google.protobuf.ProtocolStringList
          getItemsList() {
        return items_.getUnmodifiableView();
      }
      /**
       * <code>repeated string items = 2;</code>
       * @return The count of items.
       */
      public int getItemsCount() {
        return items_.size();
      }
      /**
       * <code>repeated string items = 2;</code>
       * @param index The index of the element to return.
       * @return The items at the given index.
       */
      public java.lang.String getItems(int index) {
        return items_.get(index);
      }
      /**
       * <code>repeated string items = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the items at the given index.
       */
      public com.google.protobuf.ByteString
          getItemsBytes(int index) {
        return items_.getByteString(index);
      }
      /**
       * <code>repeated string items = 2;</code>
       * @param index The index to set the value at.
       * @param value The items to set.
       * @return This builder for chaining.
       */
      public Builder setItems(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string items = 2;</code>
       * @param value The items to add.
       * @return This builder for chaining.
       */
      public Builder addItems(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string items = 2;</code>
       * @param values The items to add.
       * @return This builder for chaining.
       */
      public Builder addAllItems(
          java.lang.Iterable<java.lang.String> values) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string items = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearItems() {
        items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string items = 2;</code>
       * @param value The bytes of the items to add.
       * @return This builder for chaining.
       */
      public Builder addItemsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 4;</code>
       * @return The price.
       */
      @java.lang.Override
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 4;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <code>string destination = 5;</code>
       * @return The destination.
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destination_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destination = 5;</code>
       * @return The bytes for destination.
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destination = 5;</code>
       * @param value The destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        destination_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string destination = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestination() {
        destination_ = getDefaultInstance().getDestination();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string destination = 5;</code>
       * @param value The bytes for destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        destination_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.proto.Order)
    }

    // @@protoc_insertion_point(class_scope:org.example.proto.Order)
    private static final org.example.proto.OrderManagementOuterClass.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.OrderManagementOuterClass.Order();
    }

    public static org.example.proto.OrderManagementOuterClass.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.OrderManagementOuterClass.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CombinedShipmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.proto.CombinedShipment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string status = 2;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    java.util.List<org.example.proto.OrderManagementOuterClass.Order> 
        getOrdersListList();
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    org.example.proto.OrderManagementOuterClass.Order getOrdersList(int index);
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    int getOrdersListCount();
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    java.util.List<? extends org.example.proto.OrderManagementOuterClass.OrderOrBuilder> 
        getOrdersListOrBuilderList();
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    org.example.proto.OrderManagementOuterClass.OrderOrBuilder getOrdersListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.example.proto.CombinedShipment}
   */
  public static final class CombinedShipment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.proto.CombinedShipment)
      CombinedShipmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CombinedShipment.newBuilder() to construct.
    private CombinedShipment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CombinedShipment() {
      id_ = "";
      status_ = "";
      ordersList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CombinedShipment();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_CombinedShipment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_CombinedShipment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.OrderManagementOuterClass.CombinedShipment.class, org.example.proto.OrderManagementOuterClass.CombinedShipment.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <code>string status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERSLIST_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<org.example.proto.OrderManagementOuterClass.Order> ordersList_;
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.example.proto.OrderManagementOuterClass.Order> getOrdersListList() {
      return ordersList_;
    }
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.example.proto.OrderManagementOuterClass.OrderOrBuilder> 
        getOrdersListOrBuilderList() {
      return ordersList_;
    }
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    @java.lang.Override
    public int getOrdersListCount() {
      return ordersList_.size();
    }
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    @java.lang.Override
    public org.example.proto.OrderManagementOuterClass.Order getOrdersList(int index) {
      return ordersList_.get(index);
    }
    /**
     * <code>repeated .org.example.proto.Order ordersList = 3;</code>
     */
    @java.lang.Override
    public org.example.proto.OrderManagementOuterClass.OrderOrBuilder getOrdersListOrBuilder(
        int index) {
      return ordersList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      for (int i = 0; i < ordersList_.size(); i++) {
        output.writeMessage(3, ordersList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      for (int i = 0; i < ordersList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, ordersList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.OrderManagementOuterClass.CombinedShipment)) {
        return super.equals(obj);
      }
      org.example.proto.OrderManagementOuterClass.CombinedShipment other = (org.example.proto.OrderManagementOuterClass.CombinedShipment) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getOrdersListList()
          .equals(other.getOrdersListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      if (getOrdersListCount() > 0) {
        hash = (37 * hash) + ORDERSLIST_FIELD_NUMBER;
        hash = (53 * hash) + getOrdersListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.OrderManagementOuterClass.CombinedShipment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.OrderManagementOuterClass.CombinedShipment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.proto.CombinedShipment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.proto.CombinedShipment)
        org.example.proto.OrderManagementOuterClass.CombinedShipmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_CombinedShipment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_CombinedShipment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.OrderManagementOuterClass.CombinedShipment.class, org.example.proto.OrderManagementOuterClass.CombinedShipment.Builder.class);
      }

      // Construct using org.example.proto.OrderManagementOuterClass.CombinedShipment.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        status_ = "";
        if (ordersListBuilder_ == null) {
          ordersList_ = java.util.Collections.emptyList();
        } else {
          ordersList_ = null;
          ordersListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.OrderManagementOuterClass.internal_static_org_example_proto_CombinedShipment_descriptor;
      }

      @java.lang.Override
      public org.example.proto.OrderManagementOuterClass.CombinedShipment getDefaultInstanceForType() {
        return org.example.proto.OrderManagementOuterClass.CombinedShipment.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.OrderManagementOuterClass.CombinedShipment build() {
        org.example.proto.OrderManagementOuterClass.CombinedShipment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.OrderManagementOuterClass.CombinedShipment buildPartial() {
        org.example.proto.OrderManagementOuterClass.CombinedShipment result = new org.example.proto.OrderManagementOuterClass.CombinedShipment(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.example.proto.OrderManagementOuterClass.CombinedShipment result) {
        if (ordersListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            ordersList_ = java.util.Collections.unmodifiableList(ordersList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.ordersList_ = ordersList_;
        } else {
          result.ordersList_ = ordersListBuilder_.build();
        }
      }

      private void buildPartial0(org.example.proto.OrderManagementOuterClass.CombinedShipment result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.OrderManagementOuterClass.CombinedShipment) {
          return mergeFrom((org.example.proto.OrderManagementOuterClass.CombinedShipment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.OrderManagementOuterClass.CombinedShipment other) {
        if (other == org.example.proto.OrderManagementOuterClass.CombinedShipment.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (ordersListBuilder_ == null) {
          if (!other.ordersList_.isEmpty()) {
            if (ordersList_.isEmpty()) {
              ordersList_ = other.ordersList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOrdersListIsMutable();
              ordersList_.addAll(other.ordersList_);
            }
            onChanged();
          }
        } else {
          if (!other.ordersList_.isEmpty()) {
            if (ordersListBuilder_.isEmpty()) {
              ordersListBuilder_.dispose();
              ordersListBuilder_ = null;
              ordersList_ = other.ordersList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              ordersListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrdersListFieldBuilder() : null;
            } else {
              ordersListBuilder_.addAllMessages(other.ordersList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                org.example.proto.OrderManagementOuterClass.Order m =
                    input.readMessage(
                        org.example.proto.OrderManagementOuterClass.Order.parser(),
                        extensionRegistry);
                if (ordersListBuilder_ == null) {
                  ensureOrdersListIsMutable();
                  ordersList_.add(m);
                } else {
                  ordersListBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 2;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<org.example.proto.OrderManagementOuterClass.Order> ordersList_ =
        java.util.Collections.emptyList();
      private void ensureOrdersListIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          ordersList_ = new java.util.ArrayList<org.example.proto.OrderManagementOuterClass.Order>(ordersList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.example.proto.OrderManagementOuterClass.Order, org.example.proto.OrderManagementOuterClass.Order.Builder, org.example.proto.OrderManagementOuterClass.OrderOrBuilder> ordersListBuilder_;

      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public java.util.List<org.example.proto.OrderManagementOuterClass.Order> getOrdersListList() {
        if (ordersListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ordersList_);
        } else {
          return ordersListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public int getOrdersListCount() {
        if (ordersListBuilder_ == null) {
          return ordersList_.size();
        } else {
          return ordersListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public org.example.proto.OrderManagementOuterClass.Order getOrdersList(int index) {
        if (ordersListBuilder_ == null) {
          return ordersList_.get(index);
        } else {
          return ordersListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder setOrdersList(
          int index, org.example.proto.OrderManagementOuterClass.Order value) {
        if (ordersListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersListIsMutable();
          ordersList_.set(index, value);
          onChanged();
        } else {
          ordersListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder setOrdersList(
          int index, org.example.proto.OrderManagementOuterClass.Order.Builder builderForValue) {
        if (ordersListBuilder_ == null) {
          ensureOrdersListIsMutable();
          ordersList_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder addOrdersList(org.example.proto.OrderManagementOuterClass.Order value) {
        if (ordersListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersListIsMutable();
          ordersList_.add(value);
          onChanged();
        } else {
          ordersListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder addOrdersList(
          int index, org.example.proto.OrderManagementOuterClass.Order value) {
        if (ordersListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersListIsMutable();
          ordersList_.add(index, value);
          onChanged();
        } else {
          ordersListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder addOrdersList(
          org.example.proto.OrderManagementOuterClass.Order.Builder builderForValue) {
        if (ordersListBuilder_ == null) {
          ensureOrdersListIsMutable();
          ordersList_.add(builderForValue.build());
          onChanged();
        } else {
          ordersListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder addOrdersList(
          int index, org.example.proto.OrderManagementOuterClass.Order.Builder builderForValue) {
        if (ordersListBuilder_ == null) {
          ensureOrdersListIsMutable();
          ordersList_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder addAllOrdersList(
          java.lang.Iterable<? extends org.example.proto.OrderManagementOuterClass.Order> values) {
        if (ordersListBuilder_ == null) {
          ensureOrdersListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ordersList_);
          onChanged();
        } else {
          ordersListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder clearOrdersList() {
        if (ordersListBuilder_ == null) {
          ordersList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          ordersListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public Builder removeOrdersList(int index) {
        if (ordersListBuilder_ == null) {
          ensureOrdersListIsMutable();
          ordersList_.remove(index);
          onChanged();
        } else {
          ordersListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public org.example.proto.OrderManagementOuterClass.Order.Builder getOrdersListBuilder(
          int index) {
        return getOrdersListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public org.example.proto.OrderManagementOuterClass.OrderOrBuilder getOrdersListOrBuilder(
          int index) {
        if (ordersListBuilder_ == null) {
          return ordersList_.get(index);  } else {
          return ordersListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public java.util.List<? extends org.example.proto.OrderManagementOuterClass.OrderOrBuilder> 
           getOrdersListOrBuilderList() {
        if (ordersListBuilder_ != null) {
          return ordersListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ordersList_);
        }
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public org.example.proto.OrderManagementOuterClass.Order.Builder addOrdersListBuilder() {
        return getOrdersListFieldBuilder().addBuilder(
            org.example.proto.OrderManagementOuterClass.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public org.example.proto.OrderManagementOuterClass.Order.Builder addOrdersListBuilder(
          int index) {
        return getOrdersListFieldBuilder().addBuilder(
            index, org.example.proto.OrderManagementOuterClass.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.proto.Order ordersList = 3;</code>
       */
      public java.util.List<org.example.proto.OrderManagementOuterClass.Order.Builder> 
           getOrdersListBuilderList() {
        return getOrdersListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.example.proto.OrderManagementOuterClass.Order, org.example.proto.OrderManagementOuterClass.Order.Builder, org.example.proto.OrderManagementOuterClass.OrderOrBuilder> 
          getOrdersListFieldBuilder() {
        if (ordersListBuilder_ == null) {
          ordersListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.example.proto.OrderManagementOuterClass.Order, org.example.proto.OrderManagementOuterClass.Order.Builder, org.example.proto.OrderManagementOuterClass.OrderOrBuilder>(
                  ordersList_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          ordersList_ = null;
        }
        return ordersListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.proto.CombinedShipment)
    }

    // @@protoc_insertion_point(class_scope:org.example.proto.CombinedShipment)
    private static final org.example.proto.OrderManagementOuterClass.CombinedShipment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.OrderManagementOuterClass.CombinedShipment();
    }

    public static org.example.proto.OrderManagementOuterClass.CombinedShipment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CombinedShipment>
        PARSER = new com.google.protobuf.AbstractParser<CombinedShipment>() {
      @java.lang.Override
      public CombinedShipment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CombinedShipment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CombinedShipment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.OrderManagementOuterClass.CombinedShipment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_CombinedShipment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_CombinedShipment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026order_management.proto\022\021org.example.pr" +
      "oto\032\036google/protobuf/wrappers.proto\"[\n\005O" +
      "rder\022\n\n\002id\030\001 \001(\t\022\r\n\005items\030\002 \003(\t\022\023\n\013descr" +
      "iption\030\003 \001(\t\022\r\n\005price\030\004 \001(\002\022\023\n\013destinati" +
      "on\030\005 \001(\t\"\\\n\020CombinedShipment\022\n\n\002id\030\001 \001(\t" +
      "\022\016\n\006status\030\002 \001(\t\022,\n\nordersList\030\003 \003(\0132\030.o" +
      "rg.example.proto.Order2\205\003\n\017OrderManageme" +
      "nt\022B\n\010addOrder\022\030.org.example.proto.Order" +
      "\032\034.google.protobuf.StringValue\022B\n\010getOrd" +
      "er\022\034.google.protobuf.StringValue\032\030.org.e" +
      "xample.proto.Order\022H\n\014searchOrders\022\034.goo" +
      "gle.protobuf.StringValue\032\030.org.example.p" +
      "roto.Order0\001\022H\n\014updateOrders\022\030.org.examp" +
      "le.proto.Order\032\034.google.protobuf.StringV" +
      "alue(\001\022V\n\rprocessOrders\022\034.google.protobu" +
      "f.StringValue\032#.org.example.proto.Combin" +
      "edShipment(\0010\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_org_example_proto_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_proto_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_Order_descriptor,
        new java.lang.String[] { "Id", "Items", "Description", "Price", "Destination", });
    internal_static_org_example_proto_CombinedShipment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_proto_CombinedShipment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_CombinedShipment_descriptor,
        new java.lang.String[] { "Id", "Status", "OrdersList", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
